In [2]:
import numpy as np

In [3]:
import numpy as np

def create_magic_like(n):
    magic_square = np.zeros((n, n), dtype=int)

    row, col = 0, n // 2
    num = 1

    while num <= n * n:
        magic_square[row, col] = num
        num += 1

        new_row, new_col = (row - 1) % n, (col + 1) % n

        if magic_square[new_row, new_col]:
            row += 1
        else:
            row, col = new_row, new_col

    return magic_square

# Generate a 5x5 "magic-like" matrix
A = create_magic_like(5)

# Define column vector b
b = np.array([10, 26, 42, 59, 38])

# Print matrix A and vector b
print("Matrix A:")
print(A)

print("\nVector b:", b)


Matrix A:
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]

Vector b: [10 26 42 59 38]


In [4]:
# Solve the system Ax = b using numpy's solve function
x = np.linalg.solve(A, b)
# Print the solution vector x
print("\nSolution vector x:")
print(x)


Solution vector x:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]


In [5]:
# Calculate the residual r = A*x - b
r = np.dot(A, x) - b
# Print the residual vector r
print("\nResidual vector r:")
print(r)



Residual vector r:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.10542736e-15]


In [6]:
import scipy.linalg
# Perform LU decomposition of A
P, L, U = scipy.linalg.lu(A) # Note: Use scipy.linalg.lu for LU decomposition
# Solve the system Ax = b using LU decomposition
x1 = np.linalg.solve(A, b)
# Calculate the error between solutions
err1 = np.dot(A, x1) - b
# Print matrices P, L, U and vectors x1, err1
print("Matrix P (Permutation matrix):")
print(P)
print("\nMatrix L (Lower triangular matrix):")
print(L)
print("\nMatrix U (Upper triangular matrix):")
print(U)
print("\nSolution vector x1:")
print(x1)
print("\nError vector err1:")
print(err1)

Matrix P (Permutation matrix):
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Matrix L (Lower triangular matrix):
[[1.         0.         0.         0.         0.        ]
 [0.73913043 1.         0.         0.         0.        ]
 [0.47826087 0.76873662 1.         0.         0.        ]
 [0.17391304 0.25267666 0.5163652  1.         0.        ]
 [0.43478261 0.48394004 0.72308355 0.92307692 1.        ]]

Matrix U (Upper triangular matrix):
[[ 23.           5.           7.          14.          16.        ]
 [  0.          20.30434783  -4.17391304  -2.34782609   3.17391304]
 [  0.           0.          24.8608137   -2.89079229  -1.09207709]
 [  0.           0.           0.          19.65116279  18.97932817]
 [  0.           0.           0.           0.         -22.22222222]]

Solution vector x1:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Error vector err1:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.

In [7]:
# Solve the system Ax = b using numpy's least squares function
y = np.linalg.lstsq(A, b, rcond=None)[0]
# Print the solution vector y
print("\nSolution vector y:")
print(y)



Solution vector y:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]


In [8]:
# Solve the system Ax = b using matrix inverse
A_inv = np.linalg.inv(A)
x2 = np.dot(A_inv, b)
# Calculate the residual r2 and error err2
r2 = np.dot(A, x2) - b
err2 = x - x2
# Print solution vector x2, residual r2 and error err2
print("\nSolution vector x2using inverse:")
print(x2)
print("\nResidual vector r2:")
print(r2)
print("\nError vector err2:")
print(err2)



Solution vector x2using inverse:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r2:
[-3.55271368e-15 -3.55271368e-15 -7.10542736e-15  0.00000000e+00
 -7.10542736e-15]

Error vector err2:
[-7.63278329e-17  4.16333634e-17  0.00000000e+00  4.44089210e-16
  5.55111512e-17]


In [9]:
import numpy as np

def rref(A):
    """ Computes the reduced row echelon form (RREF) of a matrix A.
    Parameters:
    A : numpy.ndarray
        Input matrix of shape (m, n)
    Returns:
    R : numpy.ndarray
        Reduced row echelon form of matrix A
    """
    A = A.astype(float)
    m, n = A.shape
    lead = 0
    
    for r in range(m):
        if lead >= n:
            break
            
        if A[r, lead] == 0:
            for i in range(r + 1, m):
                if A[i, lead] != 0:
                    A[[r, i]] = A[[i, r]]
                    break
                    
        if A[r, lead] != 0:
            A[r] = A[r] / A[r, lead]
            for i in range(m):
                if i != r:
                    A[i] -= A[i, lead] * A[r]
                    
        lead += 1
        
    return A

In [10]:
# Compute reduced row echelon form of [A | b]
C = np.hstack((A, b[:, np.newaxis]))
R = rref(C)

# Extract solution vector x3 from the RREF matrix
x3 = R[:, -1]

# Calculate residuals r3 = Ax3 - b
r3 = np.dot(A, x3) - b

# Calculate error vector (difference between true solution x and computed x3)
err3 = x - x3

print("\nSolution vector x3 (from RREF):")
print(x3)
print("\nResidual vector r3 (from RREF):")
print(r3)
print("\nError vector err3 (difference between x and x3):")
print(err3)


Solution vector x3 (from RREF):
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r3 (from RREF):
[1.77635684e-15 7.10542736e-15 0.00000000e+00 2.13162821e-14
 0.00000000e+00]

Error vector err3 (difference between x and x3):
[-2.67147415e-16  9.71445147e-17  0.00000000e+00 -4.44089210e-16
  2.22044605e-16]


In [11]:
import time
# Initialize Num
Num = 500
# Generate matrix A and vector b
A = np.random.rand(Num, Num) + Num * np.eye(Num)
b = np.random.rand(Num, 1)
# Method 1: Solve using backslash operator
start_time = time.time()
x1 = np.linalg.solve(A, b)
end_time = time.time()
time_backslash = end_time - start_time
# Method 2: Solve using matrix inverse
start_time = time.time()
x2 = np.linalg.inv(A) @ b
end_time = time.time()
time_inv = end_time - start_time
# Method 3: Solve using reduced row echelon form (rref)
start_time = time.time()
C = np.hstack((A, b))
R = rref(C)
x3 = R[:, -1]
end_time = time.time()
time_rref = end_time - start_time
# Print the solution vectors and computational times
print("\nSolution vector x1 (using backslash operator):")
print(x1)
47
print("\nSolution vector x2 (using matrix inverse):")
print(x2)
print("\nSolution vector x3 (using reduced row echelon form):")
print(x3)
print("\nComputational times:")
print(f"Backslash operator: {time_backslash} seconds")
print(f"Matrix inverse: {time_inv} seconds")
print(f"Reduced row echelon form (rref): {time_rref} seconds")



Solution vector x1 (using backslash operator):
[[ 5.28580878e-04]
 [ 5.65890231e-04]
 [ 1.97289508e-04]
 [ 9.88281835e-04]
 [ 1.26310995e-03]
 [-9.03737689e-05]
 [ 1.96890679e-04]
 [ 9.49976424e-04]
 [ 4.44117110e-04]
 [ 6.85335041e-04]
 [ 5.24407582e-04]
 [ 1.24558700e-03]
 [-3.15874305e-04]
 [ 1.67379548e-03]
 [ 1.52792759e-03]
 [ 3.62457497e-04]
 [ 7.82057705e-04]
 [ 1.64130355e-03]
 [ 1.13808051e-03]
 [ 4.55882964e-05]
 [-2.69804607e-04]
 [ 1.18503508e-03]
 [ 4.93366480e-04]
 [ 1.42389023e-03]
 [ 1.24396261e-03]
 [ 1.51921353e-03]
 [ 9.48024105e-04]
 [ 9.58574035e-05]
 [ 1.57739836e-03]
 [-2.46207862e-04]
 [ 6.19640880e-04]
 [ 1.58312634e-03]
 [ 1.60952894e-03]
 [ 1.15851644e-03]
 [ 3.50549413e-04]
 [-2.84260414e-04]
 [ 1.02947945e-03]
 [ 1.58048092e-03]
 [ 1.08879576e-03]
 [ 3.81172543e-04]
 [ 8.17853687e-04]
 [-9.52704727e-05]
 [ 1.14419478e-03]
 [-2.41253176e-04]
 [ 1.37109173e-03]
 [ 8.17495770e-06]
 [ 6.95528697e-04]
 [ 1.24020934e-04]
 [ 1.30103969e-03]
 [ 8.97766176e-04]
 [

In [12]:
import numpy as np

# Define matrix A and vector b for the overdetermined system
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 10], 
              [9, 11, 12]])

b = np.array([1, 2, 3, 4]).reshape(-1, 1)  # Reshape b to be a column vector

# Solve the system Ax = b using the backslash operator (least squares)
x = np.linalg.lstsq(A, b, rcond=None)[0]

# Calculate the residual r = Ax - b
r = np.dot(A, x) - b

# Print the solution vector x
print("\nSolution vector x:")
print(x)

# Print the residual vector r
print("\nResidual vector r:")
print(r)

# Calculate and print the solution using normal equations for comparison
ATA_inv = np.linalg.inv(np.dot(A.T, A))  # Calculate (A.T * A)^(-1)
ATb = np.dot(A.T, b)  # Calculate A.T * b
y = np.dot(ATA_inv, ATb)  # Solve normal equations A.T * A * y = A.T * b

# Calculate the difference between x and y to verify accuracy
err = x - y

# Print the solution vector y from normal equations
print("\nSolution vector y (from normal equations):")
print(y)

# Print the difference vector err (should be close to zero)
print("\nDifference vector err (x - y):")
print(err)


Solution vector x:
[[-0.24630542]
 [ 0.38916256]
 [ 0.16256158]]

Residual vector r:
[[ 0.01970443]
 [-0.06403941]
 [ 0.01477833]
 [ 0.01477833]]

Solution vector y (from normal equations):
[[-0.24630542]
 [ 0.38916256]
 [ 0.16256158]]

Difference vector err (x - y):
[[-1.13797860e-15]
 [-3.75255382e-14]
 [ 1.19071419e-14]]


In [13]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

b = np.array([1, 3, 5, 7])  # Now b has 4 elements
  # No need to reshape, keeping as a 1D array

# Solve the system Ax = b using the least squares method
x = np.linalg.lstsq(A, b, rcond=None)[0]

# Calculate the residual r1 = Ax - b
r1 = np.dot(A, x) - b

# Print the solution vector x
print("\nSolution vector x:")
print(x)

# Print the residual vector r1
print("\nResidual vector r1:")
print(r1)

# Obtain another particular solution using the pseudoinverse pinv(A)
A_pinv = np.linalg.pinv(A)
y = np.dot(A_pinv, b)

# Calculate the residual r2 = Ax - b for solution y
r2 = np.dot(A, y) - b

# Print the solution vector y from pseudoinverse
print("\nSolution vector y (from pseudoinverse):")
print(y)

# Print the residual vector r2
print("\nResidual vector r2:")
print(r2)



Solution vector x:
[0.38888889 0.22222222 0.05555556]

Residual vector r1:
[8.8817842e-16 8.8817842e-16 8.8817842e-16 0.0000000e+00]

Solution vector y (from pseudoinverse):
[0.38888889 0.22222222 0.05555556]

Residual vector r2:
[ 1.55431223e-15 -4.44089210e-16 -2.66453526e-15 -4.44089210e-15]


In [14]:
import numpy as np
from scipy.linalg import null_space  # Corrected import

# Example matrix A
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Obtain the complete set of solutions using the null space of A
null_space_matrix = null_space(A)

# Arbitrary constant C (should match the number of columns in null_space_matrix)
C = np.array([1])  # Adjusted to match the column count

# Calculate the complete solution z = null_space(A) * C
z = np.dot(null_space_matrix, C)

# Print the complete solution vector z
print("\nComplete solution vector z:")
print(z)



Complete solution vector z:
[-0.40824829  0.81649658 -0.40824829]
