In [3]:
import numpy as np
A = np.array([[1, 2, -10, 4], [3, 4, 5, -6], [3, 3, -2, 5]])
B = np.array([3, 3, 4, 2])
print("A:", A)
print("B:", B)

A: [[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]]
B: [3 3 4 2]


In [6]:
# function to determine length
def length(matrix):
    return max(matrix.shape)
# Length of A and B
lengthA = length(A)
lengthB = length(B)
print("lengthA:", lengthA)
print("lengthB:", lengthB)

lengthA: 4
lengthB: 4


In [7]:
# Add B as the fourth row of A and create the new matrix C
C = np.vstack((A, B))
print("C:", C)

C: [[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]
 [  3   3   4   2]]


In [8]:
# Create D from rows 2, 3, 4 and columns 3, 4 of C
D = C[1:4, 2:4]
print("D:", D)
Variables: D

D: [[ 5 -6]
 [-2  5]
 [ 4  2]]


In [9]:
# Transpose D to create E
E = D.T
print("E:", E)

E: [[ 5 -2  4]
 [-6  5  2]]


In [11]:
# Check the size of E
m, n = E.shape
print("m:", m)
print("n:", n)

m: 2
n: 3


In [13]:
# Create equally spaced vectors using arange and linspace
EqualSpaced = np.arange(0, 2 * np.pi, np.pi / 10)
EqualSpaced1 = np.linspace(0, 2 * np.pi, 21)
print("EqualSpaced:", EqualSpaced)
print("EqualSpaced1:", EqualSpaced1)

EqualSpaced: [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604]
EqualSpaced1: [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604 6.28318531]


In [15]:
# Find the maximum and minimum in each column of A
maxcolA = np.max(A, axis=0)
mincolA = np.min(A, axis=0)
print("maxcolA:", maxcolA)
print("mincolA:", mincolA)

maxcolA: [3 4 5 5]
mincolA: [  1   2 -10  -6]


In [16]:
# Find the maximum and minimum in each row of A
maxrowA = np.max(A, axis=1)
minrowA = np.min(A, axis=1)
# Find the maximum and minimum elements in the entire matrix A
maxA = np.max(A)
minA = np.min(A)
print("maxrowA:", maxrowA)
print("minrowA:", minrowA)
print("maxA:", maxA)
print("minA:", minA)

maxrowA: [4 5 5]
minrowA: [-10  -6  -2]
maxA: 5
minA: -10


In [19]:
# Calculate mean and sum in each column and row of A
meancolA = np.mean(A, axis=0)
meanrowA = np.mean(A, axis=1)
sumcolA = np.sum(A, axis=0)
sumrowA = np.sum(A, axis=1)
# Calculate mean and sum of all elements in A
meanA = np.mean(A)
sumA = np.sum(A)
print("meancolA:", meancolA)
print("meanrowA:", meanrowA)
print("sumcolA:", sumcolA)
print("sumrowA:", sumrowA)
print("meanA:", meanA)

meancolA: [ 2.33333333  3.         -2.33333333  1.        ]
meanrowA: [-0.75  1.5   2.25]
sumcolA: [ 7  9 -7  3]
sumrowA: [-3  6  9]
meanA: 1.0


In [20]:
# Create matrices F and G with random integers from -4 to 4
F = np.random.randint(-4, 5, (5, 3))
G = np.random.randint(-4, 5, (5, 3))
print("F:", F)
print("G:", G)

F: [[ 1  1  2]
 [ 1  4  0]
 [ 2 -2 -4]
 [ 1 -2  0]
 [ 3 -2  4]]
G: [[ 1  3 -2]
 [-3  3  2]
 [ 1 -3  0]
 [-1 -3  4]
 [ 1  1 -2]]


In [22]:
# Perform scalar multiplication, addition, subtraction, and element-wise multiplication on F and G
ScMultF = 0.4 * F
SumFG = F + G
DiffFG = F - G
ElProdFG = F * G
print("ScMultF:", ScMultF)
print("SumFG:", SumFG)
print("DiffFG:", DiffFG)
print("ElProdFG:", ElProdFG)

ScMultF: [[ 0.4  0.4  0.8]
 [ 0.4  1.6  0. ]
 [ 0.8 -0.8 -1.6]
 [ 0.4 -0.8  0. ]
 [ 1.2 -0.8  1.6]]
SumFG: [[ 2  4  0]
 [-2  7  2]
 [ 3 -5 -4]
 [ 0 -5  4]
 [ 4 -1  2]]
DiffFG: [[ 0 -2  4]
 [ 4  1 -2]
 [ 1  1 -4]
 [ 2  1 -4]
 [ 2 -3  6]]
ElProdFG: [[ 1  3 -4]
 [-3 12  0]
 [ 2  6  0]
 [-1  6  0]
 [ 3 -2 -8]]


In [25]:
# Check the size of F 
sizeF = F.shape
sizeA = A.shape
print("sizeF:", sizeF)
print("sizeA:", sizeA)

sizeF: (5, 3)
sizeA: (3, 4)


In [27]:
# Perform matrix multiplication of F and A if dimensions are compatible
if sizeF[1] == sizeA[0]:
    H = F @ A
    print("H:", H)
else:
    print("Cannot multiply F and A due to incompatible dimensions.")

H: [[ 10  12  -9   8]
 [ 13  18  10 -20]
 [-16 -16 -22   0]
 [ -5  -6 -20  16]
 [  9  10 -48  44]]


In [28]:
# Generate the identity matrix with 3 rows and 3 columns
eye33 = np.eye(3)
print("eye33:", eye33)

eye33: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# Generate matrices of zeros with size 5x3 and ones with size 4x2
zeros53 = np.zeros((5, 3))
ones42 = np.ones((4, 2))
print("zeros53:", zeros53)
print("ones42:", ones42)

zeros53: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones42: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [33]:
# Generate a diagonal matrix S with the diagonal elements 1, 2, 7
S = np.diag([1, 2, 7])
print("S:", S)

S: [[1 0 0]
 [0 2 0]
 [0 0 7]]


In [35]:
# Extract the diagonal elements from a random 6x6 matrix
R = np.random.rand(6, 6)
diagR = np.diag(R)
print("R:", R)
print("diagR:", diagR)

R: [[0.16226377 0.65341643 0.86449464 0.18903341 0.44460324 0.63042851]
 [0.23035967 0.38148344 0.15937264 0.39421354 0.66522932 0.53341004]
 [0.63040204 0.52162832 0.609662   0.53664909 0.12296551 0.25426507]
 [0.79525655 0.25757019 0.72323724 0.5327975  0.30349005 0.06125677]
 [0.66301873 0.4715359  0.90176286 0.85339946 0.0579648  0.76787098]
 [0.69533427 0.40877224 0.4279919  0.14680036 0.07241521 0.42011208]]
diagR: [0.16226377 0.38148344 0.609662   0.5327975  0.0579648  0.42011208]


In [38]:
# Create a sparse diagonal matrix and convert to dense
from scipy.sparse import diags
diag121 = diags([-np.ones(10), 2*np.ones(10), -np.ones(10)], [-1, 0, 1], shape=(10,
10)).todense()
print("diag121:", diag121)

diag121: [[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2.]]
